spring:
  application:
    name: pet-api
  lifecycle:
    timeout-per-shutdown-phase: 30s
  boot:
    admin:
      client:
        url: http://localhost:8080/spring-admin
        instance:
          prefer-ip: true
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
        username: ${SPRING_ADMIN_USERNAME:admin}
        password: ${SPRING_ADMIN_PASSWORD:admin}
  security:
    user:
      name: ${SPRING_ADMIN_CLIENT_USERNAME:client}
      password: ${SPRING_ADMIN_CLIENT_PASSWORD:client}

  datasource:
    url: jdbc:postgresql://localhost:5434/pets_db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.format_sql: true
      hibernate.generate_statistics: true
      hibernate.use_sql_comments: true



server:
  port: 8081
  shutdown: graceful
  servlet:
    context-path: /pet-api

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
