---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-api-app
    spec:
      containers:
        - image: pylypchenko/user-api:1.0.0
          name: user-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-api-config
          env:
            - name: SPRING_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-storage
                  key: SPRING_ADMIN_USERNAME
            - name: SPRING_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-storage
                  key: SPRING_ADMIN_PASSWORD
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8090
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8090
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
...
