---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
data:
  SPRING_PROFILES_ACTIVE: prod
  JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=80 -XX:InitialHeapSize=256m -XX:MaxHeapSize=512m
  SERVER_SERVLET_CONTEXT_PATH: /spring-admin

