---
apiVersion: v1
kind: Secret
metadata:
  name: secret-storage
stringData:
  SPRING_ADMIN_USERNAME: admin
  SPRING_ADMIN_PASSWORD: admin
  SPRING_ADMIN_CLIENT_USERNAME: client
  SPRING_ADMIN_CLIENT_PASSWORD: client
  POSTGRES_DB_HOST: jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/pets_db
  POSTGRES_DB_USERNAME: postgres
  POSTGRES_DB_PASSWORD: postgres
...
